### ISSUE TITLE
Value None for field 'from' is not of type 'string' (0)

### ISSUE THREAD

**Issue by Juje** [gorkalaucirica/HipchatAPIv2Client#27]
The from in the Message model is null by default but since yesterday (07-10-2015) this started throwing the following error:

    Value None for field 'from' is not of type 'string' (0)

And when I changed the value null to an empty string:

    protected $from = '';

Everything worked again.

The code I am talking about can be found at: [Model/Message.php#L20](Model/Message.php#L20)

**Comment by vlChris** [comment]
Yeah same thing happened to me this morning.... I just wrote a setFrom method into the Message model this morning.. 6 in one I guess. Easier to just create an empty from property heh.

**Comment by coreycwgriffin** [comment]
Having the same issue, and replacing the $from variable with a blank string also worked for me.

**Comment by gorkalaucirica** [comment]
Fixed in #29
